version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 
    commands:
  pre_build:
    commands:
  build:
    commands:
artifacts:
  base-directory: dist/cradleofbooks
  files:
    - '**/*'
